### ISSUE TITLE
¿Bug in online KNN eval?

### ISSUE THREAD

**Issue by juanCarlosWheat** [DonkeyShot21/cassle#4]
Hello,

Congrats for your paper! It touches very interesting questions and I'd love to further study the problem of CSSL!

I am trying to execute your script for training barlow twins `python job_launcher.py --script bash_files/continual/cifar/barlow_distill.sh`, but I might have encountered a bug: if I train with the WeightedKNNClassifier for performance monitor, your code calls its forward [here](https://github.com/DonkeyShot21/cassle/blob/d25f9c7cb5e822660dc1ef03e7fac09a33d0b1a8/cassle/methods/base.py#L432) with only the `train_features` and `target_features` provided.
After that, the compute function breaks down [here at line 89](https://github.com/DonkeyShot21/cassle/blob/d25f9c7cb5e822660dc1ef03e7fac09a33d0b1a8/cassle/utils/knn.py#L89) because `self.test_features` is an empty list.

Am I getting something wrong? I am working in a new conda env with setup as specified in your README file.

Muchas gracias!

**Comment by vturrisi** [comment]
Hi. @DonkeyShot21 can you check this?

**Comment by DonkeyShot21** [comment]
Hi Juan Carlos! Thanks for your interest in the paper.

It actually should provide the `test_features` as well at this line https://github.com/DonkeyShot21/cassle/blob/d25f9c7cb5e822660dc1ef03e7fac09a33d0b1a8/cassle/methods/base.py#L464

if you have `online_eval` disabled it makes sense that online knn breaks, so make sure that you are indeed passing a meaningful `online_eval_batch_size`.

**Comment by juanCarlosWheat** [comment]
Oh great!
Thanks again!
