### ISSUE TITLE
Task_id set to zero as first task SSL

### ISSUE THREAD

**Issue by KameniAlexNea** [DonkeyShot21/cassle#7]
https://github.com/DonkeyShot21/cassle/blob/ba739c8376bdc4d16acda3d143088569a56d18f4/bash_files/continual/cifar/barlow_distill.sh#L8

Hi,
I want to be sure that setting the first task of distillation process as zero isn't an error, since you have already learned this as SSL in normal process.
What can be the goal of this, please ?

Thanks

**Comment by DonkeyShot21** [comment]
Hi, it's a typo, it should be set to 1.

**Comment by KameniAlexNea** [comment]
Noted, thank you
